name: CI - Deploy to AWS S3

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: CI - Zip and Upload to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"

      - name: Zip the Application
        run: |
          zip -r app.zip . -x "*.git*" ".github/*" "node_modules/*"

      - name: Upload ZIP to S3
        run: |
          TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
          S3_BUCKET="simple-node-app-bucket"
          S3_KEY="app-$TIMESTAMP.zip"

          aws s3 cp app.zip s3://$S3_BUCKET/$S3_KEY

          echo "S3_KEY=$S3_KEY" >> $GITHUB_ENV

      - name: Set S3_KEY as Output
        id: output
        run: echo "::set-output name=S3_KEY::$S3_KEY"

    outputs:
      s3_key: ${{ steps.output.outputs.S3_KEY }}
